export const about = {
  path: '/about/',
  name: 'About',
  title: 'About Zeron | Native, Open Source Coding Agent Workspace',
  description: 'Meet Zeron: a native workspace for coding agents, built in Rust with GPUI. Local by default, with optional device sync and open source contributions.',
};

export function aboutContent(hero) {
  return `${hero('Your agents. Your machines. One workspace.', 'Zeron brings coding agents into a native interface you can use across your devices.')}
<section class="about-story"><div class="wrap agent-reading"><h2><b>A place for the whole workflow.</b> From the first prompt to the final diff.</h2><div><p>Coding with agents means more than sending a prompt. It means following conversations, checking tool activity, reviewing changes, and keeping track of work across repositories.</p><p>Zeron brings those pieces together. Choose the harness that fits the task and keep a familiar workspace as you move between agents and machines.</p><a class="text-link" href="/agents/">Explore the integrations <span class="ui-icon" data-icon="arrow-up-right" aria-hidden="true"></span></a></div></div></section>
<section class="agent-section"><div class="wrap"><div class="sec-head"><h2><b>Built close to the machine.</b> Open at every layer.</h2></div><div class="agent-steps"><article><span class="agent-step-number">01</span><h3>A native foundation.</h3><p>The desktop interface is built in Rust with GPUI. A separate engine runs the agents, so work can live on your desktop or an always-on server.</p></article><article><span class="agent-step-number">02</span><h3>Local by default.</h3><p>Start using Zeron locally without an account. Sessions stay on the execution device. Sign in when you want optional multi-device sync.</p></article><article><span class="agent-step-number">03</span><h3>Yours to build on.</h3><p>Zeron is open source and MIT licensed. Read the code, build it yourself, and help shape the tools you use every day.</p><a class="text-link" href="https://github.com/zeronsh/zeron">Explore the source <span class="ui-icon" data-icon="arrow-up-right" aria-hidden="true"></span></a></article></div></div></section>
<section class="agent-section agent-related" id="contributors"><div class="wrap agent-reading"><h2><b>Built with contributors.</b> There’s room for your contribution.</h2><div><p>Every focused fix, clear bug report, and improvement to the docs helps. You can contribute to the interface, agent integrations, platform support, or the engine behind it all.</p><p>For a larger change, start with an issue or draft pull request to discuss the approach. Keep each pull request focused on one concern, and check the contribution guide for setup and testing.</p><div class="about-links"><a class="text-link" href="https://github.com/zeronsh/zeron/blob/main/CONTRIBUTORS.md">Contribution guide <span class="ui-icon" data-icon="arrow-up-right" aria-hidden="true"></span></a><a class="text-link" href="https://github.com/zeronsh/zeron/graphs/contributors">Meet the contributors <span class="ui-icon" data-icon="arrow-up-right" aria-hidden="true"></span></a><a class="text-link" href="https://github.com/zeronsh/zeron/issues">Find an issue <span class="ui-icon" data-icon="arrow-up-right" aria-hidden="true"></span></a></div></div></div></section>`;
}
