// Search intent research: docs/seo-keywords.md. Order matches the homepage.
export const agents = [
  {
    slug: 'claude-code', name: 'Claude Code', icon: 'claude',
    title: 'Claude Code GUI & Desktop Client | Zeron',
    description: 'Run Claude Code in Zeron’s native desktop GUI. Organize sessions, inspect branch diffs, and control work across your synced machines.',
    heading: 'A native GUI for Claude Code.',
    intro: 'Keep Claude Code’s work in view. Zeron brings conversations, tool activity, and branch diffs into one desktop workspace, alongside your other coding agents.',
    angle: 'From a terminal session to a workspace',
    detail: 'When several repositories need attention, terminal tabs make it easy to lose track of which task belongs where. Zeron groups Claude Code sessions by workspace so you can return to the conversation and inspect the files that changed.',
    integration: 'Zeron connects directly to Claude Code’s stream-json protocol. Claude Code remains the agent doing the work; Zeron provides the interface around its conversation and tool activity.',
    setup: 'Install and authenticate Claude Code on the machine that will run your tasks. In Zeron, enable Claude Code, open a workspace, and choose it for a new session.',
    question: 'Is Zeron the official Claude Code desktop app?',
    answer: 'No. Zeron is an independent, open-source client that supports Claude Code alongside other agents. Your Claude Code authentication and provider access are still required.',
    docs: 'https://code.claude.com/docs/en/overview',
  },
  {
    slug: 'cursor', name: 'Cursor', icon: 'cursor',
    title: 'Cursor CLI GUI & Agent Workspace | Zeron',
    description: 'Use Cursor’s agent in Zeron’s native desktop workspace. Follow sessions, review code changes, and manage Cursor alongside other coding agents.',
    heading: 'A workspace for your Cursor agent.',
    intro: 'Bring Cursor’s agent workflow into Zeron. Keep tasks organized by repository and review the changes from the same window you use for your other agents.',
    angle: 'Keep agent work organized across projects',
    detail: 'Use Cursor for one task and another harness for the next without scattering their conversations across separate interfaces. Zeron gives each workspace a session list and a place to inspect its branch changes.',
    integration: 'Zeron connects to Cursor through a pinned Cursor SDK shim. This integration runs the agent workflow; it does not embed the Cursor editor or reproduce its editor extensions.',
    setup: 'Install and authenticate the Cursor agent on the host machine. Enable Cursor in Zeron, open the repository you want to work on, and select Cursor when starting a session.',
    question: 'Does Zeron replace the Cursor editor?',
    answer: 'Zeron is a separate interface for agent sessions. You can keep using your editor for direct code editing and use Zeron to organize agent work and inspect branch diffs.',
    docs: 'https://cursor.com/docs/cli/overview',
  },
  {
    slug: 'codex', name: 'Codex', icon: 'openai',
    title: 'Codex GUI for macOS, Windows & Linux | Zeron',
    description: 'Run OpenAI Codex in a native desktop GUI on macOS, Windows, or Linux. Manage workspaces, review branch diffs, and follow synced sessions with Zeron.',
    heading: 'Codex, in a shared agent workspace.',
    intro: 'Use Codex from a native desktop interface built for your repositories. Keep conversations, tool activity, and changed files together, with other harnesses close at hand.',
    angle: 'One place to follow Codex work',
    detail: 'A coding task rarely ends with the answer in chat. Zeron puts the workspace’s branch diff and commit history beside the session workflow so you can inspect what changed before deciding what to do next.',
    integration: 'Zeron talks directly to Codex through its app-server JSON-RPC protocol. Codex performs the agent work using its own authentication; Zeron organizes the sessions and presents their activity.',
    setup: 'Install Codex and complete its authentication on the execution machine. Enable Codex in Zeron, open a workspace, and select Codex for your session.',
    question: 'Can I use Zeron as a Codex GUI on Linux?',
    answer: 'Yes. Zeron provides Linux x64 and ARM64 downloads, as well as macOS Apple silicon and Windows x64 builds. Install and authenticate Codex on the machine that runs your tasks.',
    docs: 'https://developers.openai.com/codex/cli/',
  },
  {
    slug: 'opencode', name: 'OpenCode', icon: 'opencode',
    title: 'OpenCode Desktop Client & GUI | Zeron',
    description: 'Use OpenCode in Zeron’s native desktop client. Organize coding sessions, review branch changes, and work with multiple agent harnesses in one app.',
    heading: 'An OpenCode GUI with room for every agent.',
    intro: 'Give OpenCode a place in your everyday workspace. Zeron brings its conversations and tool activity together with session lists, branch diffs, and commit history.',
    angle: 'Keep the agent, share the workspace',
    detail: 'You do not need to settle on a single harness for every repository. Run OpenCode where it fits your work and keep its sessions in the same interface as Claude Code, Codex, and the rest of your agents.',
    integration: 'Zeron uses OpenCode’s own HTTP and server-sent event protocol. The connection follows the agent’s structured events rather than rendering a terminal inside the app.',
    setup: 'Install OpenCode and configure its provider access on the execution machine. Enable OpenCode in Zeron, choose a workspace, and start a session with OpenCode selected.',
    question: 'Does this connect to any existing OpenCode server?',
    answer: 'This page describes Zeron’s managed OpenCode integration. For remote work, use Zeron’s optional device sync with an engine on the execution machine; do not assume that an arbitrary OpenCode server URL can be attached.',
    docs: 'https://opencode.ai/docs/',
  },
  {
    slug: 'antigravity', name: 'Antigravity', icon: 'antigravity',
    title: 'Antigravity Agent Client & GUI | Zeron',
    description: 'Use Google Antigravity’s agent through Zeron’s desktop interface. Keep agent sessions and branch diffs together with your other coding harnesses.',
    heading: 'Antigravity in your agent workspace.',
    intro: 'Bring Google Antigravity’s agent into Zeron and keep its work alongside your other harnesses. Follow the conversation and review changes without losing track of the repository.',
    angle: 'A common interface for agent work',
    detail: 'Switching harnesses should not mean reorganizing your projects. Zeron keeps the workspace and session structure consistent when you choose Antigravity for a task.',
    integration: 'Zeron connects through Google’s Antigravity ACP server, agy_acp_server. This is an agent integration, not an embedded copy of the Antigravity IDE or a generic wrapper around its terminal.',
    setup: 'Enable Antigravity in Zeron and complete the required provider authentication. The integration uses the Antigravity ACP server; a standalone CLI installation alone is not the same connection.',
    question: 'Does Zeron include the Antigravity IDE?',
    answer: 'No. Zeron provides its own workspace interface around the Antigravity agent connection. IDE-specific panels, extensions, and workflows are not implied by this integration.',
    docs: 'https://antigravity.google/docs/ide/extensions',
  },
  {
    slug: 'devin', name: 'Devin', icon: 'devin',
    title: 'Devin CLI Client & Desktop GUI | Zeron',
    description: 'Work with Devin CLI in Zeron’s native desktop GUI. Organize repository sessions, follow agent activity, and review branch changes in one place.',
    heading: 'A desktop workspace for Devin CLI.',
    intro: 'Bring Devin CLI sessions into Zeron. Keep each conversation attached to its workspace, follow the agent’s activity, and inspect the branch as the work develops.',
    angle: 'Follow the work in its repository',
    detail: 'Use a session list to return to the right task, then inspect the workspace’s diff and history. Devin can sit alongside other coding harnesses without requiring a separate organization system for each one.',
    integration: 'Zeron launches Devin CLI through its Agent Client Protocol connection, devin acp. This page covers that CLI integration, not management of the separate Devin cloud dashboard.',
    setup: 'Install Devin CLI and authenticate with the access it requires. Enable Devin in Zeron, open a workspace, and choose Devin for a new coding session.',
    question: 'Does Zeron import my Devin cloud sessions?',
    answer: 'The integration described here runs Devin CLI through ACP. It does not promise to import or control sessions from the Devin cloud dashboard.',
    docs: 'https://docs.devin.ai/cli',
  },
  {
    slug: 'hermes', name: 'Hermes', icon: 'hermes',
    title: 'Hermes Agent GUI & Desktop Client | Zeron',
    description: 'Use Hermes Agent in Zeron’s native desktop GUI. Keep repository sessions, tool activity, and branch diffs alongside your other coding agents.',
    heading: 'A native workspace for Hermes Agent.',
    intro: 'Give Hermes coding sessions a clear home. Zeron keeps the conversation, workspace, and code changes together while you move between tasks and agent harnesses.',
    angle: 'Focus Hermes on a coding workspace',
    detail: 'When you use Hermes for repository work, Zeron provides the surrounding session list and Git views. Return to a task, follow its activity, and inspect the branch changes from one desktop interface.',
    integration: 'Zeron connects to Hermes through hermes acp. Hermes remains responsible for its agent runtime and provider configuration; Zeron presents the session through a shared workspace interface.',
    setup: 'Install Hermes Agent and configure its provider access. Enable Hermes in Zeron, open your repository, and start a session with Hermes selected.',
    question: 'Does Zeron expose every Hermes gateway feature?',
    answer: 'This integration is for Hermes agent sessions over ACP. Hermes messaging gateways and its own desktop-specific controls are separate features, not automatically part of Zeron.',
    docs: 'https://hermes-agent.nousresearch.com/docs/',
  },
  {
    slug: 'pi', name: 'Pi', icon: 'pi',
    title: 'Pi Coding Agent GUI & Desktop App | Zeron',
    description: 'Use the Pi coding agent in Zeron’s native desktop app. Organize sessions, inspect branch diffs, and keep Pi alongside other coding harnesses.',
    heading: 'A desktop GUI for the Pi coding agent.',
    intro: 'Keep Pi’s coding work in a native workspace. Zeron adds a shared session list and Git views around the agent, so you can follow a task from conversation to code changes.',
    angle: 'Pi sessions with the repository in view',
    detail: 'Zeron gives Pi the same workspace structure as your other harnesses. Use it for a focused task, revisit the conversation later, and inspect the branch without searching through terminal tabs.',
    integration: 'Zeron connects through the community pi-acp adapter. The Pi CLI is still required; Zeron can install its pinned adapter when npm is available. Pi keeps its own provider and model configuration.',
    setup: 'Install the Pi coding agent and configure its provider and model. Enable Pi in Zeron with npm available for the adapter, then open a workspace and select Pi for a session.',
    question: 'Is this the Pi chatbot or a coding agent?',
    answer: 'This integration is for the Pi coding agent CLI. It is unrelated to the consumer chatbot named Pi. You need the coding agent installed on the execution machine.',
    docs: 'https://github.com/earendil-works/pi',
  },
  {
    slug: 'grok', name: 'Grok', icon: 'grok',
    title: 'Grok Build GUI & CLI Desktop Client | Zeron',
    description: 'Run the Grok coding agent in Zeron’s native desktop GUI. Follow CLI agent sessions, inspect branch changes, and organize work across repositories.',
    heading: 'A desktop GUI for Grok coding sessions.',
    intro: 'Bring Grok’s coding agent into Zeron. Follow the conversation and tool activity in a workspace that also keeps your branch diff and other agent sessions within reach.',
    angle: 'An interface for code, tools, and tasks',
    detail: 'Keep repository work separate from general chat. Zeron’s Grok integration is designed for coding sessions on your machine, with a session list and Git views around the work.',
    integration: 'Zeron launches the Grok CLI through grok agent stdio and reads its Agent Client Protocol events. The CLI does the agent work; Zeron provides the desktop interface.',
    setup: 'Install the Grok CLI and configure the authentication it requires. Enable Grok in Zeron, open your repository, and choose Grok when starting a session.',
    question: 'Is this a desktop wrapper for grok.com?',
    answer: 'No. This is an integration with the Grok coding agent CLI. It does not embed grok.com or promise the consumer app’s chat, image, or video features.',
    docs: 'https://docs.x.ai/build/overview',
  },
];
