// Compile reviewed geometry for the native renderer. No network or dependencies.
const fs=require('fs'),path=require('path'),G=require('./motion-geometry.js');
const root=__dirname,out=path.resolve(root,'../../crates/ui/assets/custom-icons');
const icons=JSON.parse(fs.readFileSync(root+'/catalog.json')),motions=JSON.parse(fs.readFileSync(root+'/motions.json')),inventory=JSON.parse(fs.readFileSync(root+'/inventory.json'));
fs.mkdirSync(out+'/small',{recursive:true});
for(const i of icons)for(const [src,dest] of [['svg',''],['svg-small','small/']])fs.copyFileSync(`${root}/${src}/${i.name}.svg`,`${out}/${dest}${i.name}.svg`);
const names=new Map();
for(const i of inventory.desktop)names.set(i.constant,i.custom?`custom-icons/${i.custom}.svg`:`icons/${i.asset}.svg`);
for(const i of icons){const name=i.name.toUpperCase().replaceAll('-','_');if(!names.has(name))names.set(name,`custom-icons/${i.name}.svg`)}
fs.writeFileSync(path.resolve(out,'../../src/icons/generated.rs'),'// Generated by apps/icon-lab/export-native.cjs.\n'+[...names].map(([n,p])=>`pub const ${n}: &str = "${p}";`).join('\n')+'\n');
const by=Object.fromEntries(icons.map(i=>[i.name,i]));
const svg=(ps,small=false)=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="${small?1.75:1.5}" stroke-linecap="round" stroke-linejoin="round">${ps.map(p=>`<path d="${p.d}" fill="white" fill-opacity="${p.fill||0}" opacity="${p.opacity??1}"${p.stroke===0?' stroke="none"':''}/>`).join('')}</svg>`;
const nativeMotions=[...motions,{fromIcon:"appearance-system",toIcon:"sun",duration:320,mode:"handoff"}];
const frames=nativeMotions.map(m=>{const plan=G.plan(by[m.fromIcon].paths,by[m.toIcon].paths,m);return {from:`custom-icons/${m.fromIcon}.svg`,to:`custom-icons/${m.toIcon}.svg`,duration:m.duration,frames:Array.from({length:97},(_,j)=>svg(G.frame(plan,j/96))),smallFrames:Array.from({length:97},(_,j)=>svg(G.frame(G.plan(by[m.fromIcon].smallPaths,by[m.toIcon].smallPaths,m),j/96),true))}});
fs.writeFileSync(out+'/../icon-motions.json',JSON.stringify(frames)+'\n');
console.log(`Exported ${icons.length} native icon pairs and ${frames.length} bounded vector transitions.`);

fs.appendFileSync(path.resolve(out,'../../src/icons/generated.rs'), '\npub const MORPH_PATHS: &[&str] = &[\n'+[...new Set(nativeMotions.flatMap(m=>[m.fromIcon,m.toIcon]))].map(n=>`    "custom-icons/${n}.svg",`).join('\n')+'\n];\n');
