//! Bounded SVG frame bank generated by the gallery's exact Bézier engine.
//! 97 vector poses per transition limit raster-cache keys independently of FPS.
use serde::Deserialize;
use std::{borrow::Cow, sync::OnceLock, time::Instant};

#[derive(Deserialize)]
pub(super) struct Transition {
    pub from: String,
    pub to: String,
    pub duration: f64,
    pub frames: Vec<String>,
}
pub(super) fn transitions() -> &'static [Transition] {
    static BANK: OnceLock<Vec<Transition>> = OnceLock::new();
    BANK.get_or_init(|| {
        serde_json::from_str(include_str!("../../assets/icon-motions.json"))
            .expect("verified native icon bank")
    })
}
pub(super) fn asset(key: &str) -> Option<Cow<'static, [u8]>> {
    let (motion, pose) = key.strip_suffix(".svg")?.split_once('/')?;
    Some(Cow::Borrowed(
        transitions()
            .get(motion.parse::<usize>().ok()?)?
            .frames
            .get(pose.parse::<usize>().ok()?)?
            .as_bytes(),
    ))
}

#[derive(Clone, Debug)]
pub(super) struct State {
    path: &'static str,
    motion: Option<usize>,
    value: f64,
    target: f64,
    velocity: f64,
    time: Instant,
}
impl State {
    pub fn new(path: &'static str, now: Instant) -> Self {
        Self {
            path,
            motion: None,
            value: 0.,
            target: 0.,
            velocity: 0.,
            time: now,
        }
    }
    fn sample(&mut self, now: Instant) {
        let dt = now.saturating_duration_since(self.time).as_secs_f64();
        self.time = now;
        if let Some(index) = self.motion {
            let w = 9250. / transitions()[index].duration;
            let error = self.value - self.target;
            let c = self.velocity + w * error;
            let decay = (-w * dt).exp();
            self.value = self.target + (error + c * dt) * decay;
            self.velocity = (self.velocity - w * c * dt) * decay;
            if !(0. ..=1.).contains(&self.value) {
                self.value = self.value.clamp(0., 1.);
                self.velocity = 0.;
            }
            if (self.value - self.target).abs() < 0.001 && self.velocity.abs() < 0.035 {
                self.value = self.target;
                self.velocity = 0.;
            }
        }
    }
    pub fn update(&mut self, path: &'static str, reduced: bool, now: Instant) -> Option<String> {
        self.sample(now);
        if reduced {
            *self = Self::new(path, now);
            return None;
        }
        if path != self.path {
            let matching = self
                .motion
                .filter(|&i| {
                    let m = &transitions()[i];
                    (m.from == path || m.to == path) && (m.from == self.path || m.to == self.path)
                })
                .or_else(|| {
                    transitions().iter().position(|m| {
                        (m.from == self.path && m.to == path)
                            || (m.to == self.path && m.from == path)
                    })
                });
            if let Some(index) = matching {
                let m = &transitions()[index];
                if self.motion != Some(index) {
                    self.value = if self.path == m.to { 1. } else { 0. };
                    self.velocity = 0.;
                }
                self.target = if path == m.to { 1. } else { 0. };
                self.motion = Some(index);
                self.path = path;
            } else {
                *self = Self::new(path, now);
            }
        }
        let index = self.motion?;
        if self.value == self.target && self.velocity == 0. {
            return None;
        }
        let pose = (self.value * 96.).round() as usize;
        Some(format!("icon-motion/{index}/{pose}.svg"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;
    #[test]
    fn reversals_preserve_position_and_velocity_and_settle() {
        let now = Instant::now();
        let mut s = State::new(super::super::SUN, now);
        assert!(s.update(super::super::MOON, false, now).is_some());
        let mid = now + Duration::from_millis(60);
        s.update(super::super::MOON, false, mid);
        let (value, velocity) = (s.value, s.velocity);
        s.update(super::super::SUN, false, mid);
        assert_eq!((s.value, s.velocity), (value, velocity));
        assert!(
            s.update(super::super::SUN, false, now + Duration::from_secs(2))
                .is_none()
        );
        assert_eq!(s.value, 0.);
    }
    #[test]
    fn initial_mount_reduced_motion_and_unrelated_changes_are_static() {
        let now = Instant::now();
        let mut s = State::new(super::super::SUN, now);
        assert!(s.update(super::super::SUN, false, now).is_none());
        assert!(s.update(super::super::MOON, true, now).is_none());
        assert!(s.update(super::super::FOLDER, false, now).is_none());
    }
    #[test]
    fn native_bank_is_complete_and_bounded() {
        assert_eq!(transitions().len(), 37);
        for (i, m) in transitions().iter().enumerate() {
            assert_eq!(m.frames.len(), 97);
            for j in 0..97 {
                let bytes = asset(&format!("{i}/{j}.svg")).unwrap();
                usvg::Tree::from_data(&bytes, &usvg::Options::default()).unwrap();
            }
        }
        assert!(asset("0/97.svg").is_none());
        assert!(asset("37/0.svg").is_none());
    }
}
