// Generated by apps/icon-lab/export-native.cjs.
pub const PROJECT_DEFAULT: &str = "custom-icons/project.svg";
pub const REMOTE_SERVER: &str = "custom-icons/server.svg";
pub const FAST_TIER: &str = "custom-icons/bolt.svg";
pub const MONITOR: &str = "custom-icons/monitor.svg";
pub const SUN: &str = "custom-icons/sun.svg";
pub const MOON: &str = "custom-icons/moon.svg";
pub const GLOBE: &str = "custom-icons/globe.svg";
pub const LAPTOP: &str = "custom-icons/laptop.svg";
pub const PEN_NEW_SQUARE: &str = "custom-icons/compose.svg";
pub const SORT: &str = "custom-icons/sort.svg";
pub const MORE_HORIZONTAL: &str = "custom-icons/more.svg";
pub const SORT_VERTICAL: &str = "custom-icons/sort-ascending.svg";
pub const DRAG_HANDLE: &str = "custom-icons/drag.svg";
pub const QUEUE_DRAG_HANDLE: &str = "custom-icons/drag.svg";
pub const QUEUE_SEND: &str = "custom-icons/send-now.svg";
pub const QUEUE_CHECK: &str = "custom-icons/check.svg";
pub const QUEUE_CLOSE: &str = "custom-icons/close.svg";
pub const QUEUE_PAPERCLIP: &str = "custom-icons/paperclip.svg";
pub const CLOCK_CIRCLE: &str = "custom-icons/clock.svg";
pub const CALENDAR: &str = "custom-icons/calendar.svg";
pub const LIST: &str = "custom-icons/list.svg";
pub const FOLDER_WITH_FILES: &str = "custom-icons/repository.svg";
pub const FILE_TREE: &str = "custom-icons/file-tree.svg";
pub const FOLDER: &str = "custom-icons/folder.svg";
pub const FLOPPY_DISK: &str = "custom-icons/save.svg";
pub const GIT_BRANCH: &str = "custom-icons/branch.svg";
pub const PULL_REQUEST: &str = "custom-icons/pull-request.svg";
pub const CLOUD: &str = "custom-icons/cloud.svg";
pub const TAG: &str = "custom-icons/tag.svg";
pub const SIDEBAR_MINIMALISTIC: &str = "custom-icons/panel-right-open.svg";
pub const SIDEBAR_MINIMALISTIC_LEFT: &str = "custom-icons/panel-left-open.svg";
pub const KEY_MINIMALISTIC: &str = "custom-icons/key.svg";
pub const KEYBOARD: &str = "custom-icons/keyboard.svg";
pub const ARROW_LEFT: &str = "custom-icons/arrow-left.svg";
pub const ARROW_RIGHT: &str = "custom-icons/arrow-right.svg";
pub const ARROW_UP: &str = "custom-icons/arrow-up.svg";
pub const ARROW_DOWN: &str = "custom-icons/arrow-down.svg";
pub const ARROW_UP_RIGHT: &str = "custom-icons/arrow-up-right.svg";
pub const RETURN: &str = "custom-icons/return.svg";
pub const ALT_ARROW_DOWN: &str = "custom-icons/chevron-down.svg";
pub const ALT_ARROW_UP: &str = "custom-icons/chevron-up.svg";
pub const EXPAND_ARROWS: &str = "custom-icons/expand.svg";
pub const COLLAPSE_ARROWS: &str = "custom-icons/collapse.svg";
pub const FOLD_VERTICAL: &str = "custom-icons/fold.svg";
pub const SPLIT_COLUMNS: &str = "custom-icons/split.svg";
pub const WRAP_TEXT: &str = "custom-icons/wrap.svg";
pub const ALT_ARROW_LEFT: &str = "custom-icons/chevron-left.svg";
pub const ALT_ARROW_RIGHT: &str = "custom-icons/chevron-right.svg";
pub const SMARTPHONE: &str = "custom-icons/phone.svg";
pub const ARCHIVE_UP_MINIMALISTIC: &str = "custom-icons/unarchive.svg";
pub const REFRESH: &str = "custom-icons/refresh.svg";
pub const RESTART: &str = "custom-icons/restart.svg";
pub const ADD_CIRCLE: &str = "custom-icons/add.svg";
pub const TUNING: &str = "custom-icons/tuning.svg";
pub const EYE: &str = "custom-icons/eye.svg";
pub const EYE_CLOSED: &str = "custom-icons/eye-closed.svg";
pub const PAPERCLIP: &str = "custom-icons/paperclip.svg";
pub const PIN: &str = "custom-icons/pin.svg";
pub const PEN: &str = "custom-icons/edit.svg";
pub const ARCHIVE_MINIMALISTIC: &str = "custom-icons/archive.svg";
pub const TRASH_BIN_MINIMALISTIC: &str = "custom-icons/trash.svg";
pub const SETTINGS_MINIMALISTIC: &str = "custom-icons/settings.svg";
pub const LOGOUT_2: &str = "custom-icons/logout.svg";
pub const MAGNIFER: &str = "custom-icons/search.svg";
pub const PALETTE_SEARCH: &str = "custom-icons/search.svg";
pub const COMMAND: &str = "custom-icons/command.svg";
pub const DOCUMENT: &str = "custom-icons/document.svg";
pub const DOCUMENT_ADD: &str = "custom-icons/document-add.svg";
pub const FILE_CODE: &str = "custom-icons/file-code.svg";
pub const FILE_STYLE: &str = "custom-icons/file-style.svg";
pub const FILE_DATA: &str = "custom-icons/file-data.svg";
pub const FILE_MARKDOWN: &str = "custom-icons/file-markdown.svg";
pub const FILE_IMAGE: &str = "custom-icons/file-image.svg";
pub const GLOBAL: &str = "custom-icons/globe.svg";
pub const CHECKLIST: &str = "custom-icons/checklist.svg";
pub const WIDGET: &str = "custom-icons/grid.svg";
pub const MAGIC_STICK_3: &str = "custom-icons/skills.svg";
pub const WIFI_OFF: &str = "custom-icons/wifi-off.svg";
pub const CLOSE_CIRCLE: &str = "custom-icons/error.svg";
pub const INFO_CIRCLE: &str = "custom-icons/info.svg";
pub const DANGER_TRIANGLE: &str = "custom-icons/warning.svg";
pub const CHAT_ROUND_LINE: &str = "custom-icons/chat.svg";
pub const BOT: &str = "custom-icons/agent.svg";
pub const BELL: &str = "custom-icons/bell.svg";
pub const VOLUME_LOUD: &str = "custom-icons/volume.svg";
pub const TERMINAL: &str = "custom-icons/terminal.svg";
pub const PLUS: &str = "custom-icons/plus.svg";
pub const CLOSE: &str = "custom-icons/close.svg";
pub const WINDOW_MINIMIZE: &str = "custom-icons/window-minimize.svg";
pub const WINDOW_MAXIMIZE: &str = "custom-icons/window-maximize.svg";
pub const WINDOW_RESTORE: &str = "custom-icons/window-restore.svg";
pub const HARD_DRIVE: &str = "custom-icons/drive.svg";
pub const HOME: &str = "custom-icons/home.svg";
pub const STOP: &str = "custom-icons/stop.svg";
pub const CHECK: &str = "custom-icons/check.svg";
pub const COPY: &str = "custom-icons/copy.svg";
pub const ACTION_PLAY: &str = "custom-icons/play.svg";
pub const ACTION_TEST: &str = "custom-icons/test.svg";
pub const ACTION_LINT: &str = "custom-icons/lint.svg";
pub const ACTION_CONFIGURE: &str = "custom-icons/configure.svg";
pub const ACTION_BUILD: &str = "custom-icons/build.svg";
pub const ACTION_DEBUG: &str = "custom-icons/debug.svg";
pub const STAR: &str = "custom-icons/star.svg";
pub const STAR_BOLD: &str = "custom-icons/star-active.svg";
pub const ZERON_LOGO: &str = "icons/zeron-logo.svg";
pub const CLAUDE_MARK: &str = "icons/claude-mark.svg";
pub const OPENAI_MARK: &str = "icons/openai-mark.svg";
pub const CURSOR_MARK: &str = "icons/cursor-mark.svg";
pub const DEVIN_MARK: &str = "icons/devin-mark.svg";
pub const GROK_MARK: &str = "icons/grok-mark.svg";
pub const HERMES_MARK: &str = "icons/hermes-mark.svg";
pub const PI_MARK: &str = "icons/pi-mark.svg";
pub const OPENCODE_MARK: &str = "icons/opencode-mark.svg";
pub const ANTIGRAVITY_MARK: &str = "icons/antigravity-mark.svg";
pub const PANEL_LEFT_OPEN: &str = "custom-icons/panel-left-open.svg";
pub const PANEL_LEFT_CLOSED: &str = "custom-icons/panel-left-closed.svg";
pub const PANEL_RIGHT_OPEN: &str = "custom-icons/panel-right-open.svg";
pub const PANEL_RIGHT_CLOSED: &str = "custom-icons/panel-right-closed.svg";
pub const PANEL_BOTTOM_OPEN: &str = "custom-icons/panel-bottom-open.svg";
pub const PANEL_BOTTOM_CLOSED: &str = "custom-icons/panel-bottom-closed.svg";
pub const CHEVRON_DOWN: &str = "custom-icons/chevron-down.svg";
pub const CHEVRON_UP: &str = "custom-icons/chevron-up.svg";
pub const CHEVRON_LEFT: &str = "custom-icons/chevron-left.svg";
pub const CHEVRON_RIGHT: &str = "custom-icons/chevron-right.svg";
pub const EXPAND: &str = "custom-icons/expand.svg";
pub const COLLAPSE: &str = "custom-icons/collapse.svg";
pub const FOLD: &str = "custom-icons/fold.svg";
pub const UNFOLD: &str = "custom-icons/unfold.svg";
pub const MENU: &str = "custom-icons/menu.svg";
pub const MORE: &str = "custom-icons/more.svg";
pub const FOLDER_OPEN: &str = "custom-icons/folder-open.svg";
pub const REPOSITORY: &str = "custom-icons/repository.svg";
pub const FOLDER_ADD: &str = "custom-icons/folder-add.svg";
pub const PROJECT: &str = "custom-icons/project.svg";
pub const PHONE: &str = "custom-icons/phone.svg";
pub const SERVER: &str = "custom-icons/server.svg";
pub const DRIVE: &str = "custom-icons/drive.svg";
pub const BROWSER: &str = "custom-icons/browser.svg";
pub const CHAT: &str = "custom-icons/chat.svg";
pub const CHATS: &str = "custom-icons/chats.svg";
pub const ARCHIVE: &str = "custom-icons/archive.svg";
pub const UNARCHIVE: &str = "custom-icons/unarchive.svg";
pub const PIN_ACTIVE: &str = "custom-icons/pin-active.svg";
pub const UNPIN: &str = "custom-icons/unpin.svg";
pub const CLOCK: &str = "custom-icons/clock.svg";
pub const SEND: &str = "custom-icons/send.svg";
pub const SEND_NOW: &str = "custom-icons/send-now.svg";
pub const PLAY: &str = "custom-icons/play.svg";
pub const PAUSE: &str = "custom-icons/pause.svg";
pub const EDIT: &str = "custom-icons/edit.svg";
pub const COMPOSE: &str = "custom-icons/compose.svg";
pub const DRAG: &str = "custom-icons/drag.svg";
pub const MICROPHONE: &str = "custom-icons/microphone.svg";
pub const MICROPHONE_OFF: &str = "custom-icons/microphone-off.svg";
pub const WAVEFORM: &str = "custom-icons/waveform.svg";
pub const LINK: &str = "custom-icons/link.svg";
pub const IMAGE: &str = "custom-icons/image.svg";
pub const IMAGE_ERROR: &str = "custom-icons/image-error.svg";
pub const SAVE: &str = "custom-icons/save.svg";
pub const TRASH: &str = "custom-icons/trash.svg";
pub const SEARCH: &str = "custom-icons/search.svg";
pub const WRAP: &str = "custom-icons/wrap.svg";
pub const UNWRAP: &str = "custom-icons/unwrap.svg";
pub const SPLIT: &str = "custom-icons/split.svg";
pub const UNIFIED: &str = "custom-icons/unified.svg";
pub const GRID: &str = "custom-icons/grid.svg";
pub const BRANCH: &str = "custom-icons/branch.svg";
pub const MERGE: &str = "custom-icons/merge.svg";
pub const COMMIT: &str = "custom-icons/commit.svg";
pub const SORT_ASCENDING: &str = "custom-icons/sort-ascending.svg";
pub const SORT_DESCENDING: &str = "custom-icons/sort-descending.svg";
pub const APPEARANCE_SYSTEM: &str = "custom-icons/appearance-system.svg";
pub const SETTINGS: &str = "custom-icons/settings.svg";
pub const KEY: &str = "custom-icons/key.svg";
pub const LOCK: &str = "custom-icons/lock.svg";
pub const UNLOCK: &str = "custom-icons/unlock.svg";
pub const LOGOUT: &str = "custom-icons/logout.svg";
pub const USER: &str = "custom-icons/user.svg";
pub const STAR_ACTIVE: &str = "custom-icons/star-active.svg";
pub const BELL_OFF: &str = "custom-icons/bell-off.svg";
pub const VOLUME: &str = "custom-icons/volume.svg";
pub const VOLUME_OFF: &str = "custom-icons/volume-off.svg";
pub const AGENT: &str = "custom-icons/agent.svg";
pub const SKILLS: &str = "custom-icons/skills.svg";
pub const BOLT: &str = "custom-icons/bolt.svg";
pub const TEST: &str = "custom-icons/test.svg";
pub const LINT: &str = "custom-icons/lint.svg";
pub const CONFIGURE: &str = "custom-icons/configure.svg";
pub const BUILD: &str = "custom-icons/build.svg";
pub const DEBUG: &str = "custom-icons/debug.svg";
pub const CHECKBOX: &str = "custom-icons/checkbox.svg";
pub const CHECKBOX_CHECKED: &str = "custom-icons/checkbox-checked.svg";
pub const WIFI: &str = "custom-icons/wifi.svg";
pub const INFO: &str = "custom-icons/info.svg";
pub const SUCCESS: &str = "custom-icons/success.svg";
pub const ERROR: &str = "custom-icons/error.svg";
pub const ADD: &str = "custom-icons/add.svg";
pub const WARNING: &str = "custom-icons/warning.svg";
pub const LOADING: &str = "custom-icons/loading.svg";
pub const PULL_REQUEST_DRAFT: &str = "custom-icons/pull-request-draft.svg";

pub const MORPH_PATHS: &[&str] = &[
    "custom-icons/sun.svg",
    "custom-icons/moon.svg",
    "custom-icons/appearance-system.svg",
    "custom-icons/panel-left-open.svg",
    "custom-icons/panel-left-closed.svg",
    "custom-icons/panel-right-open.svg",
    "custom-icons/panel-right-closed.svg",
    "custom-icons/panel-bottom-open.svg",
    "custom-icons/panel-bottom-closed.svg",
    "custom-icons/expand.svg",
    "custom-icons/collapse.svg",
    "custom-icons/window-maximize.svg",
    "custom-icons/window-restore.svg",
    "custom-icons/chevron-right.svg",
    "custom-icons/chevron-down.svg",
    "custom-icons/chevron-up.svg",
    "custom-icons/fold.svg",
    "custom-icons/unfold.svg",
    "custom-icons/unified.svg",
    "custom-icons/split.svg",
    "custom-icons/unwrap.svg",
    "custom-icons/wrap.svg",
    "custom-icons/copy.svg",
    "custom-icons/check.svg",
    "custom-icons/play.svg",
    "custom-icons/stop.svg",
    "custom-icons/send.svg",
    "custom-icons/pause.svg",
    "custom-icons/edit.svg",
    "custom-icons/close.svg",
    "custom-icons/star.svg",
    "custom-icons/star-active.svg",
    "custom-icons/pin.svg",
    "custom-icons/pin-active.svg",
    "custom-icons/unpin.svg",
    "custom-icons/eye.svg",
    "custom-icons/eye-closed.svg",
    "custom-icons/volume.svg",
    "custom-icons/volume-off.svg",
    "custom-icons/bell.svg",
    "custom-icons/bell-off.svg",
    "custom-icons/wifi.svg",
    "custom-icons/wifi-off.svg",
    "custom-icons/lock.svg",
    "custom-icons/unlock.svg",
    "custom-icons/microphone.svg",
    "custom-icons/waveform.svg",
    "custom-icons/microphone-off.svg",
    "custom-icons/checkbox.svg",
    "custom-icons/checkbox-checked.svg",
    "custom-icons/archive.svg",
    "custom-icons/unarchive.svg",
    "custom-icons/folder.svg",
    "custom-icons/folder-open.svg",
    "custom-icons/sort-ascending.svg",
    "custom-icons/sort-descending.svg",
    "custom-icons/loading.svg",
    "custom-icons/success.svg",
    "custom-icons/error.svg",
    "custom-icons/refresh.svg",
    "custom-icons/pull-request.svg",
    "custom-icons/merge.svg",
    "custom-icons/pull-request-draft.svg",
];
